SimpleWeb-ASP.NET-Core/Models/Activity.cs
using System;
using System.Collections.Generic;
using System.Linq;


namespace SimpleWeb_ASP.NET_Core.Models
{
    public class Activity
    {
        // List of Activity Types
        public enum ActivityType // enum data type - stands for enumarations type. Allows to create sets of unchanging list. 
        {
            Fitness = 1,
            Book = 2,
            Film = 3,
            TV = 4,
            VideoGame = 5,
            Meeting = 6,
            Work = 7,
            Education = 8,
            Walking = 9,
            Party = 10,

        }

        // Activity Type and Name
        public Activity(ActivityType activityType, string name = null)
        {
            Id = (int)activityType;

            // Use string if name argument unavailable
            Name = name ?? activityType.ToString(); // ??/??=  - dealing with null values (ex. if the null values is string null values, its Convert To.String vcalues).
        }
        // ACITIVITY ID
        public int Id { get; set; }
        // ACTIVITY Name
        public string Name { get; set; }
    }
}

SimpleWeb-ASP.NET-Core/Models/ErrorViewModel.cs
using System;

namespace SimpleWeb_ASP.NET_Core.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SimpleWeb-ASP.NET-Core/Models/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleWeb_ASP.NET_Core.Models
{
    public class Task
    {
        // Add a priority level to each task
        public enum PriorityLevel
        {
            Low,
            Medium,
            High
        }

        public Task() // Method Task
        {
        }

        public Task(int id, 
                    int year, 
                    int month, 
                    int day, 
                    Activity.ActivityType activityType,
                    double duration, 
                    PriorityLevel priority = PriorityLevel.Medium,
                    bool exclude = false, 
                    string notes = null)
        {
            Id = id;
            Date = new DateTime(year, month, day);
            ActivityId = (int)activityType;
            Duration = duration;
            Priority = priority;
            Exclude = exclude;
            Notes = notes;
        }

        // ID of Task
        public int Id { get; set; }
        // DATE of task
        public DateTime Date { get; set; }
        // ACTIVITY ID
        [Display(Name = "Activity")]
        public int ActivityId { get; set; }
        // ACTIVITY for task
        public Activity Activity { get; set; }
        // DURATION
        public double Duration { get; set; }
        // PRIORITY LEVEL of the task
        public PriorityLevel Priority { get; set; }
        // EXCLUDED from the total calculation (?)
        public bool Exclude { get; set; }
        // NOTES
        public string Notes { get; set; }


    }
}

SimpleWeb-ASP.NET-Core/Models/Webs.cs
using Microsoft.Extensions.ObjectPool;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;


namespace SimpleWeb_ASP.NET_Core.Models
{
    public class Webs
    {
        // Add a priority level to each Webs
        public enum PriorityLevel
        {
            Low,
            Medium,
            High
        }

        public Webs() // Method Webs
        {
        }

        public Webs(int id, 
                    int year, 
                    int month, 
                    int day, 
                    Activity.ActivityType activityType,
                    double duration, 
                    PriorityLevel priority = PriorityLevel.Medium,
                    bool exclude = false, 
                    string notes = null)
        {
            Id = id;
            Date = new DateTime(year, month, day);
            ActivityId = (int)activityType;
            Duration = duration;
            Priority = priority;
            Exclude = exclude;
            Notes = notes;
        }

        // ID of Webs
        public int Id { get; set; }
        // DATE of Webs
        public DateTime Date { get; set; }
        // ACTIVITY ID
        [Display(Name = "Activity")]
        public int ActivityId { get; set; }
        // ACTIVITY for Webs
        public Activity Activity { get; set; }
        // DURATION
        public double Duration { get; set; }
        // PRIORITY LEVEL of the Webs
        public PriorityLevel Priority { get; set; }
        // EXCLUDED from the total calculation (?)
        public bool Exclude { get; set; }
        // NOTES
        public string Notes { get; set; }


    }
}

SimpleWeb-ASP.NET-Core/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SimpleWeb_ASP.NET_Core.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SimpleWeb-ASP.NET-Core/Controllers/SimpleWebController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using SimpleWeb_ASP.NET_Core.Data;
using SimpleWeb_ASP.NET_Core.Models;


namespace SimpleWeb_ASP.NET_Core.Controllers
{
    public class SimpleWebController : Controller
    {
        private SimpleWebRepository _simpleWebRepository = null;

        public SimpleWebController()
        {
            _simpleWebRepository = new SimpleWebRepository();
        }

        public ActionResult Index()
        {
            List<Webs> simpleWeb = _simpleWebRepository.GetSimpleWeb();

            // Calculate the total activity minutes
            double totalActivity = simpleWeb
                .Where(e => e.Exclude == false) // Only include the NON Excluded entries
                .Sum(e => e.Duration);

            int numberOfSimpleWeb = simpleWeb
                .Select(e => e.Date)
                .Distinct()
                .Count();

            ViewBag.TotalActivity = totalActivity;
            ViewBag.AverageDailyActivites = (totalActivity / (double)numberOfSimpleWeb);

            return View(simpleWeb);
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new StatusCodeResult(400);
            }
            return View();
        }
    }
}

SimpleWeb-ASP.NET-Core/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Simple Web";
}

<div class="text-center">
    <h1 class="display-4">Welcome to my Page</h1>
    <p>Track your Simple Web and monitor your time spent</p>
</div>

SimpleWeb-ASP.NET-Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleWeb_ASP.NET_Core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimpleWeb_ASP.NET_Core</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SimpleWeb" asp-action="Index">Borrow Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SimpleWeb_ASP.NET_Core - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SimpleWeb-ASP.NET-Core/Views/SimpleWeb/Add.cshtml
@model SimpleWeb.Models.SimpleWeb
@{
    ViewBag.Title = "Add ToDo";
}

<h2>@ViewBag.Title</h2>

@Html.Partial("_ToDoForm")

SimpleWeb-ASP.NET-Core/Views/SimpleWeb/Index.cshtml
@model List<SimpleWeb_ASP.NET_Core.Models.Webs>
@{
    ViewBag.Title = "Simple Web";
}
 
<div class="stats">
    <h2 class="stats-header h3">Minutes of Activity</h2>
    <div class="stats-left">
        <span class="stats-number">@ViewBag.AverageDailyActivites.ToString("n1")</span> daily average
    </div>
    <div class="stats-right">
        <span class="stats-number">@ViewBag.TotalActivity.ToString("n1")</span> total
    </div>

    <h3>@ViewBag.Title</h3>

    <table class="table">
        <tr>
            <th>Date</th>
            <th>Activity</th>
            <th>Duration</th>
            <th class="hidden-xs">Intensity</th>
            <th>&nbsp;</th>
        </tr>
        @foreach (var webs in Model)
        {
            <tr>
                <td>
                    <span class="hidden-xs">@webs.Date.ToString("MM/dd/yyyy")</span>
                    <span class="hidden-sm hidden-md hidden-lg">@webs.Date.ToString("MM/dd")</span>
                </td>
                <td>@webs.Activity.Name</td>
                <td>@webs.Duration.ToString("0.0#")</td>
                <td class="hiden-xs">@webs.Priority</td>
                <td>
                    <div class="pull-right">
                        <a href="@Url.Action("Edit", new { id = webs.Id})" class="btn btn-warning btn-sm margin-right">Edit</a>
                        <a href="@Url.Action("Delete", new { id = webs.Id})" class="btn btn-danger btn-sm">Delete</a>
                    </div>
                </td>
            </tr>
        }
    </table>



</div>